---
evaluate:
  type: "shell"
  timeout: 2500
  shell:
    entrypoint: "python"
    command:
      - "/evaluate.py"
metric:
  type: "http"
  timeout: 2500
  http:
    method: "POST"
    url: "http://metrics-server:3000/api/v1/metric"
    successCodes:
      - 200
    headers:
      Content-Type: "application/json"
    parameterMode: body
runMode: "per-resource"
