FROM custompodautoscaler/python:latest

# Labels
LABEL org.opencontainers.image.source https://github.com/WatcherWhale/SecProA

# Add config, evaluator and metric gathering Py scripts
ADD config.yaml evaluate.py /
