---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
data:
  fluent.conf: |
    # Kubernetes input
    @include k8s-fluent.conf
    @include fluent-output.conf

  k8s-fluent.conf: |
    <source>
      @type tail
      read_from_head true
      tag k8s.*
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-k8s.log.pos
      exclude_path ["/var/log/containers/fluent*"]
      <parse>
        @type kubernetes
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter k8s.**>
      @type parser
      key_name log
      format json
      reserve_data true
    </filter>

    <filter k8s.**>
      @type parser
      key_name message
      format apache2
      reserve_data true
    </filter>

    <filter k8s.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>

  fluent-output.conf: |
    {{ .Values.config | nindent 4 }}
