---
- name: "Load Config on localhost"
  hosts: localhost
  tags:
    - config
  tasks:
    - name: "Load Config on localhost"
      include_vars:
        file: ./config.yml
        name: config

- import_playbook: "./kubernetes/setup.yml"
  tags:
    - setup

- import_playbook: "./autoscaler/deploy.yml"
  tags:
    - autoscaler
