---
{{- if .Values.selenium.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argus-selenium-hub
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      tolerations:
        {{- toYaml .Values.selenium.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.selenium.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.selenium.nodeSelector | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.image.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml .Values.selenium.securityContext | nindent 8 }}
      containers:
      - name: selenium-hub
        image: selenium/hub:4.1
        ports:
          - containerPort: 4444
          - containerPort: 4443
          - containerPort: 4442
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
        livenessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /wd/hub/status
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argus-selenium-chrome
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    app: selenium-node-chrome
    throughput: "5"
spec:
  replicas: {{ .Values.selenium.replicas.min }}
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: selenium-node-chrome
        image: selenium/node-chrome:4.1
        ports:
          - containerPort: 5555
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        env:
          - name: SE_EVENT_BUS_HOST
            value: "selenium-hub"
          - name: SE_EVENT_BUS_SUBSCRIBE_PORT
            value: "4443"
          - name: SE_EVENT_BUS_PUBLISH_PORT
            value: "4442"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
{{- end }}
