---
{{- if .Values.selenium.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    app: selenium-hub
spec:
  ports:
  - port: 4444
    targetPort: 4444
    name: port0
  - port: 4443
    targetPort: 4443
    name: port1
  - port: 4442
    targetPort: 4442
    name: port2
  selector:
    app: selenium-hub
{{- end }}
