---
{{- range $name, $value := .Values.services }}
{{- if not (and (eq $name "cert-master") (not $.Values.security.cluster.tls)) }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}-server"
  labels:
    {{- include "argus.labels" $ | nindent 4 }}
spec:
  selector:
    app: "{{ $name }}"
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
{{- end }}
{{- end }}
